### ISSUE TITLE
Is this library is the fork or?

### ISSUE THREAD

**Issue by AlexTrotsenko** [iagocanalejas/dualcache#7]
According to [intial commit](https://github.com/iagocanalejas/dualcache/commit/5603665210f5f8d338ae41864ec16f3eb577fcf2) it's a fork of https://github.com/vincentbrison/dualcache.

As far as I see, author of original lib is not commiting often nowday and you do. It's great, but why not create a fork and merge back your changes?

**Comment by iagocanalejas** [comment]
I made a pull request and the author didn't want some of my changes so we decided to work apart.
